@file:Suppress("RedundantVisibilityModifier")

package com.labijie.application.identity.`data`.aot

import com.labijie.infra.orm.aot.registerOrmPojoType
import java.lang.ClassLoader
import org.springframework.aot.hint.RuntimeHints
import org.springframework.aot.hint.RuntimeHintsRegistrar

/**
 * SpringBoot runtime hint for orm tables
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 *
 * Generator Version: 2.1.2
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.application.identity.data.OAuth2ClientTable
 */
internal class OrmPojoRuntimeHintsRegistrar : RuntimeHintsRegistrar {
  override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
    // Begin Table Pojo types hint register
    hints.registerOrmPojoType("com.labijie.application.identity.data.pojo.OAuth2Client")
    hints.registerOrmPojoType("com.labijie.application.identity.data.pojo.RoleClaim")
    hints.registerOrmPojoType("com.labijie.application.identity.data.pojo.Role")
    hints.registerOrmPojoType("com.labijie.application.identity.data.pojo.UserClaim")
    hints.registerOrmPojoType("com.labijie.application.identity.data.pojo.UserLogin")
    hints.registerOrmPojoType("com.labijie.application.identity.data.pojo.UserOpenId")
    hints.registerOrmPojoType("com.labijie.application.identity.data.pojo.UserRole")
    hints.registerOrmPojoType("com.labijie.application.identity.data.pojo.User")
  }
}
