server:
  port: 9898
spring:
  application:
    name: framework-dummy
  datasource:
    url: jdbc:h2:mem:testdb;mode=mysql
    username: sa
    driver-class-name: org.h2.Driver

infra:
  exposed:
    generate-schema:
      enabled: true
    show-sql: true
  oauth2:
    authorization-server:
      client-repository: memory
      default-client:
        enabled: false
application:
  httpclient:
    logger-enabled: true
  localization-service: memory
springdoc:
  api-docs:
    version: openapi_3_1
