server:
  port: 9898
spring:
  application:
    name: framework-dummy
  datasource:
    url: jdbc:h2:mem:testdb;mode=mysql
    username: sa
    driver-class-name: org.h2.Driver

infra:
  exposed:
    generate-schema: true
  oauth2:
    client-repository: memory
    default-client:
      client-id: app
      secret: 1234567
application:
  httpclient:
    logger-enabled: true
springdoc:
  api-docs:
    version: openapi_3_1
