server:
  port: 19898
spring:
  application:
    name: framework-dummy
  datasource:
    url: jdbc:h2:mem:testdb;mode=mysql
    username: sa
    driver-class-name: org.h2.Driver


infra:

  exposed:
    generate-schema:
      enabled: true
    show-sql: true
  oauth2:
    authorization-server:
      server-client:
        default-client:
          enabled: false
        repository: memory
      oauth2-client:
        oidc-login-enabled: true
application:
  httpclient:
    logger-enabled: true
  localization-service: memory
springdoc:
  api-docs:
    version: openapi_3_1
