package com.labijie.application.data.mapper;

import com.labijie.application.data.domain.FileIndex;
import com.labijie.application.data.domain.FileIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FileIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    long countByExample(FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    int deleteByExample(FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    int insert(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    int insertSelective(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    List<FileIndex> selectByExampleWithRowbounds(FileIndexExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<FileIndex> selectByExampleSelective(@Param("example") FileIndexExample example, @Param("selective") FileIndex.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    List<FileIndex> selectByExample(FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    FileIndex selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") FileIndex.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    FileIndex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FileIndex record, @Param("example") FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FileIndex record, @Param("example") FileIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<FileIndex> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<FileIndex> list, @Param("selective") FileIndex.Column ... selective);
}