package com.labijie.application.data.mapper;

import com.labijie.application.data.domain.TempFile;
import com.labijie.application.data.domain.TempFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TempFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    long countByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    int deleteByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    int insert(TempFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    int insertSelective(TempFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExampleWithRowbounds(TempFileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TempFile> selectByExampleSelective(@Param("example") TempFileExample example, @Param("selective") TempFile.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TempFile selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") TempFile.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    TempFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TempFile record, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TempFile record, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TempFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TempFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TempFile> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_temp_file
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TempFile> list, @Param("selective") TempFile.Column ... selective);
}