package com.labijie.application.order.data.mapper;

import com.labijie.application.order.data.OrderPaymentTrade;
import com.labijie.application.order.data.OrderPaymentTradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderPaymentTradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    long countByExample(OrderPaymentTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int deleteByExample(OrderPaymentTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int insert(OrderPaymentTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int insertSelective(OrderPaymentTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    List<OrderPaymentTrade> selectByExampleWithBLOBsWithRowbounds(OrderPaymentTradeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<OrderPaymentTrade> selectByExampleSelective(@Param("example") OrderPaymentTradeExample example, @Param("selective") OrderPaymentTrade.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    List<OrderPaymentTrade> selectByExampleWithBLOBs(OrderPaymentTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    List<OrderPaymentTrade> selectByExampleWithRowbounds(OrderPaymentTradeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    List<OrderPaymentTrade> selectByExample(OrderPaymentTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OrderPaymentTrade selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") OrderPaymentTrade.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    OrderPaymentTrade selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderPaymentTrade record, @Param("example") OrderPaymentTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") OrderPaymentTrade record, @Param("example") OrderPaymentTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderPaymentTrade record, @Param("example") OrderPaymentTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderPaymentTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(OrderPaymentTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderPaymentTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<OrderPaymentTrade> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<OrderPaymentTrade> list, @Param("selective") OrderPaymentTrade.Column ... selective);
}