@file:Suppress("RedundantVisibilityModifier")

package com.labijie.application.`data`.pojo.dsl

import com.labijie.application.`data`.LocalizationLanguageTable
import com.labijie.application.`data`.LocalizationLanguageTable.country
import com.labijie.application.`data`.LocalizationLanguageTable.default
import com.labijie.application.`data`.LocalizationLanguageTable.disabled
import com.labijie.application.`data`.LocalizationLanguageTable.language
import com.labijie.application.`data`.LocalizationLanguageTable.locale
import com.labijie.application.`data`.pojo.LocalizationLanguage
import com.labijie.infra.orm.OffsetList
import java.lang.IllegalArgumentException
import kotlin.Array
import kotlin.Boolean
import kotlin.Comparable
import kotlin.Int
import kotlin.Long
import kotlin.Number
import kotlin.String
import kotlin.Unit
import kotlin.collections.Collection
import kotlin.collections.Iterable
import kotlin.collections.List
import kotlin.collections.isNotEmpty
import kotlin.collections.last
import kotlin.collections.toList
import kotlin.reflect.KClass
import org.jetbrains.exposed.sql.Column
import org.jetbrains.exposed.sql.Op
import org.jetbrains.exposed.sql.Query
import org.jetbrains.exposed.sql.ResultRow
import org.jetbrains.exposed.sql.SortOrder
import org.jetbrains.exposed.sql.SqlExpressionBuilder
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.andWhere
import org.jetbrains.exposed.sql.batchInsert
import org.jetbrains.exposed.sql.batchUpsert
import org.jetbrains.exposed.sql.deleteWhere
import org.jetbrains.exposed.sql.insert
import org.jetbrains.exposed.sql.insertIgnore
import org.jetbrains.exposed.sql.replace
import org.jetbrains.exposed.sql.selectAll
import org.jetbrains.exposed.sql.statements.InsertStatement
import org.jetbrains.exposed.sql.statements.ReplaceStatement
import org.jetbrains.exposed.sql.statements.UpdateBuilder
import org.jetbrains.exposed.sql.statements.UpdateStatement
import org.jetbrains.exposed.sql.statements.UpsertBuilder
import org.jetbrains.exposed.sql.statements.UpsertStatement
import org.jetbrains.exposed.sql.update
import org.jetbrains.exposed.sql.upsert

/**
 * DSL support for LocalizationLanguageTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 *
 * Generator Version: 2.1.0
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.application.data.LocalizationLanguageTable
 */
@kotlin.Suppress(
  "unused",
  "DuplicatedCode",
  "MemberVisibilityCanBePrivate",
  "RemoveRedundantQualifierName",
)
public object LocalizationLanguageDSL {
  public val LocalizationLanguageTable.allColumns: Array<Column<*>> by lazy {
    arrayOf(
    locale,
    language,
    country,
    disabled,
    default,
    )
  }

  public fun parseRow(raw: ResultRow): LocalizationLanguage {
    val plain = LocalizationLanguage()
    plain.locale = raw[locale]
    plain.language = raw[language]
    plain.country = raw[country]
    plain.disabled = raw[disabled]
    plain.default = raw[default]
    return plain
  }

  public fun parseRowSelective(row: ResultRow): LocalizationLanguage {
    val plain = LocalizationLanguage()
    if(row.hasValue(locale)) {
      plain.locale = row[locale]
    }
    if(row.hasValue(language)) {
      plain.language = row[language]
    }
    if(row.hasValue(country)) {
      plain.country = row[country]
    }
    if(row.hasValue(disabled)) {
      plain.disabled = row[disabled]
    }
    if(row.hasValue(default)) {
      plain.default = row[default]
    }
    return plain
  }

  public fun <T> LocalizationLanguageTable.getColumnType(column: Column<T>): KClass<*> = when(column) {
    locale->String::class
    language->String::class
    country->String::class
    disabled->Boolean::class
    default->Boolean::class
    else->throw IllegalArgumentException("""Unknown column <${column.name}> for 'LocalizationLanguage'""")
  }

  private fun <T> LocalizationLanguage.getColumnValueString(column: Column<T>): String = when(column) {
    LocalizationLanguageTable.locale->this.locale
    LocalizationLanguageTable.language->this.language
    LocalizationLanguageTable.country->this.country
    LocalizationLanguageTable.disabled -> this.disabled.toString()

    LocalizationLanguageTable.default -> this.default.toString()

    else->throw IllegalArgumentException("""Can't converter value of LocalizationLanguage::${column.name} to string.""")
  }

  @kotlin.Suppress("UNCHECKED_CAST")
  private fun <T> parseColumnValue(valueString: String, column: Column<T>): T {
    val value = when(column) {
      LocalizationLanguageTable.locale -> valueString
      LocalizationLanguageTable.language -> valueString
      LocalizationLanguageTable.country -> valueString
      LocalizationLanguageTable.disabled ->valueString.toBoolean()
      LocalizationLanguageTable.default ->valueString.toBoolean()
      else->throw IllegalArgumentException("""Can't converter value of LocalizationLanguage::${column.name} to string.""")
    }
    return value as T
  }

  @kotlin.Suppress("UNCHECKED_CAST")
  public fun <T> LocalizationLanguage.getColumnValue(column: Column<T>): T = when(column) {
    LocalizationLanguageTable.locale->this.locale as T
    LocalizationLanguageTable.language->this.language as T
    LocalizationLanguageTable.country->this.country as T
    LocalizationLanguageTable.disabled->this.disabled as T
    LocalizationLanguageTable.default->this.default as T
    else->throw IllegalArgumentException("""Unknown column <${column.name}> for 'LocalizationLanguage'""")
  }

  public fun assign(
    builder: UpdateBuilder<*>,
    raw: LocalizationLanguage,
    selective: Array<out Column<*>>? = null,
    vararg ignore: Column<*>,
  ) {
    val list = if(selective.isNullOrEmpty()) null else selective
    if((list == null || list.contains(locale)) && !ignore.contains(locale))
      builder[locale] = raw.locale
    if((list == null || list.contains(language)) && !ignore.contains(language))
      builder[language] = raw.language
    if((list == null || list.contains(country)) && !ignore.contains(country))
      builder[country] = raw.country
    if((list == null || list.contains(disabled)) && !ignore.contains(disabled))
      builder[disabled] = raw.disabled
    if((list == null || list.contains(default)) && !ignore.contains(default))
      builder[default] = raw.default
  }

  public fun ResultRow.toLocalizationLanguage(vararg selective: Column<*>): LocalizationLanguage {
    if(selective.isNotEmpty()) {
      return parseRowSelective(this)
    }
    return parseRow(this)
  }

  public fun Iterable<ResultRow>.toLocalizationLanguageList(vararg selective: Column<*>): List<LocalizationLanguage> = this.map {
    it.toLocalizationLanguage(*selective)
  }

  public fun LocalizationLanguageTable.selectSlice(vararg selective: Column<*>): Query {
    val query = if(selective.isNotEmpty()) {
      select(selective.toList())
    }
    else {
      selectAll()
    }
    return query
  }

  public fun UpdateBuilder<*>.setValue(raw: LocalizationLanguage, vararg ignore: Column<*>): Unit = assign(this, raw, ignore = ignore)

  public fun UpdateBuilder<*>.setValueSelective(raw: LocalizationLanguage, vararg selective: Column<*>): Unit = assign(this, raw, selective = selective)

  public fun LocalizationLanguageTable.insert(raw: LocalizationLanguage): InsertStatement<Number> = insert {
    assign(it, raw)
  }

  public fun LocalizationLanguageTable.insertIgnore(raw: LocalizationLanguage): InsertStatement<Long> = insertIgnore {
    assign(it, raw)
  }

  public fun LocalizationLanguageTable.upsert(
    raw: LocalizationLanguage,
    onUpdateExclude: List<Column<*>>? = null,
    onUpdate: (UpsertBuilder.(UpdateStatement) -> Unit)? = null,
    `where`: (SqlExpressionBuilder.() -> Op<Boolean>)? = null,
  ): UpsertStatement<Long> = upsert(where = where, onUpdate = onUpdate, onUpdateExclude = onUpdateExclude) {
    assign(it, raw)
  }

  public fun LocalizationLanguageTable.batchInsert(
    list: Iterable<LocalizationLanguage>,
    ignoreErrors: Boolean = false,
    shouldReturnGeneratedValues: Boolean = false,
  ): List<ResultRow> {
    val rows = batchInsert(list, ignoreErrors, shouldReturnGeneratedValues) {
      entry -> assign(this, entry)
    }
    return rows
  }

  public fun LocalizationLanguageTable.batchUpsert(
    list: Iterable<LocalizationLanguage>,
    onUpdateExclude: List<Column<*>>? = null,
    onUpdate: (UpsertBuilder.(UpdateStatement) -> Unit)? = null,
    shouldReturnGeneratedValues: Boolean = false,
    `where`: (SqlExpressionBuilder.() -> Op<Boolean>)? = null,
  ): List<ResultRow> {
    val rows =  batchUpsert(data = list, keys = arrayOf(locale), onUpdate = onUpdate, onUpdateExclude = onUpdateExclude, where = where, shouldReturnGeneratedValues = shouldReturnGeneratedValues) {
      data: LocalizationLanguage-> assign(this, data)
    }
    return rows
  }

  public fun LocalizationLanguageTable.update(
    raw: LocalizationLanguage,
    selective: Array<out Column<*>>? = null,
    ignore: Array<out Column<*>>? = null,
    limit: Int? = null,
    `where`: SqlExpressionBuilder.() -> Op<Boolean>,
  ): Int = update(`where`, limit) {
    val ignoreColumns = ignore ?: arrayOf()
    assign(it, raw, selective = selective, *ignoreColumns)
  }

  public fun LocalizationLanguageTable.updateByPrimaryKey(raw: LocalizationLanguage, vararg selective: Column<*>): Int = update(raw, selective = selective, ignore = arrayOf(locale)) {
    LocalizationLanguageTable.locale.eq(raw.locale)
  }

  public fun LocalizationLanguageTable.updateByPrimaryKey(locale: String, builder: LocalizationLanguageTable.(UpdateStatement) -> Unit): Int = update({ LocalizationLanguageTable.locale.eq(locale) }, body = builder)

  public fun LocalizationLanguageTable.deleteByPrimaryKey(locale: String): Int = deleteWhere {
    LocalizationLanguageTable.locale.eq(locale)
  }

  public fun LocalizationLanguageTable.selectByPrimaryKey(locale: String, vararg selective: Column<*>): LocalizationLanguage? {
    val query = selectSlice(*selective).andWhere {
      LocalizationLanguageTable.locale.eq(locale)
    }
    return query.firstOrNull()?.toLocalizationLanguage(*selective)
  }

  public fun LocalizationLanguageTable.selectByPrimaryKeys(ids: Iterable<String>, vararg selective: Column<*>): List<LocalizationLanguage> {
    val query = selectSlice(*selective).andWhere {
      LocalizationLanguageTable.locale inList ids
    }
    return query.toLocalizationLanguageList(*selective)
  }

  public fun LocalizationLanguageTable.selectMany(vararg selective: Column<*>, `where`: Query.() -> Query?): List<LocalizationLanguage> {
    val query = selectSlice(*selective)
    `where`.invoke(query)
    return query.toLocalizationLanguageList(*selective)
  }

  public fun LocalizationLanguageTable.selectOne(vararg selective: Column<*>, `where`: Query.() -> Query?): LocalizationLanguage? {
    val query = selectSlice(*selective)
    `where`.invoke(query)
    return query.firstOrNull()?.toLocalizationLanguage(*selective)
  }

  public fun LocalizationLanguageTable.selectForwardByPrimaryKey(
    forwardToken: String? = null,
    order: SortOrder = SortOrder.DESC,
    pageSize: Int = 50,
    selective: Collection<Column<*>> = listOf(),
    `where`: (Query.() -> Query?)? = null,
  ): OffsetList<LocalizationLanguage> {
    if(pageSize < 1) {
      return OffsetList.empty()
    }
    val offsetKey = forwardToken?.let { OffsetList.decodeToken(it).firstOrNull()?.ifBlank { null } }
    val query = selectSlice(*selective.toTypedArray())
    offsetKey?.let {
      val keyValue = parseColumnValue(it, locale)
      when(order) {
        SortOrder.DESC, SortOrder.DESC_NULLS_FIRST, SortOrder.DESC_NULLS_LAST->
        query.andWhere { locale less keyValue }
        else-> query.andWhere { locale greater keyValue }
      }
    }
    `where`?.invoke(query)
    val sorted = query.orderBy(locale, order)
    val list = sorted.limit(pageSize + 1).toLocalizationLanguageList(*selective.toTypedArray()).toMutableList()
    val dataCount = list.size
    val token = if(dataCount > pageSize) {
      list.removeLast()
      val idString = list.last().getColumnValueString(locale)
      OffsetList.encodeToken(idString)
    }
    else {
      null
    }
    return OffsetList(list, token)
  }

  public fun <T : Comparable<T>> LocalizationLanguageTable.selectForward(
    sortColumn: Column<T>,
    forwardToken: String? = null,
    order: SortOrder = SortOrder.DESC,
    pageSize: Int = 50,
    selective: Collection<Column<*>> = listOf(),
    `where`: (Query.() -> Query?)? = null,
  ): OffsetList<LocalizationLanguage> {
    if(pageSize < 1) {
      return OffsetList.empty()
    }
    if(sortColumn == locale) {
      return this.selectForwardByPrimaryKey(forwardToken, order, pageSize, selective, `where`)
    }
    val kp = forwardToken?.let { if(it.isNotBlank()) OffsetList.decodeToken(it) else null }
    val offsetKey = if(!kp.isNullOrEmpty()) parseColumnValue(kp.first(), sortColumn) else null
    val lastId = if(kp != null && kp.size > 1 && kp[1].isNotBlank()) parseColumnValue(kp[1], locale) else null
    val query = selectSlice(*selective.toTypedArray())
    offsetKey?.let {
      when(order) {
        SortOrder.DESC, SortOrder.DESC_NULLS_FIRST, SortOrder.DESC_NULLS_LAST->
        query.andWhere { sortColumn lessEq it }
        else-> query.andWhere { sortColumn greaterEq it }
      }
    }
    lastId?.let {
      when(order) {
        SortOrder.DESC, SortOrder.DESC_NULLS_FIRST, SortOrder.DESC_NULLS_LAST->
        query.andWhere { locale less it }
        else-> query.andWhere { locale greater it }
      }
    }
    `where`?.invoke(query)
    val sorted = query.orderBy(Pair(sortColumn, order), Pair(locale, order))
    val list = sorted.limit(pageSize + 1).toLocalizationLanguageList(*selective.toTypedArray()).toMutableList()
    val dataCount = list.size
    val token = if(dataCount > pageSize) {
      list.removeLast()
      val idToEncode = list.last().getColumnValueString(locale)
      val sortKey = list.last().getColumnValueString(sortColumn)
      OffsetList.encodeToken(arrayOf(sortKey, idToEncode))
    }
    else null
    return OffsetList(list, token)
  }

  public fun LocalizationLanguageTable.replace(raw: LocalizationLanguage): ReplaceStatement<Long> = replace {
    assign(it, raw)
  }
}
