package com.labijie.application.order.data;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OrderPaymentTradeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public OrderPaymentTradeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderIsNull() {
            addCriterion("payment_provider is null");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderIsNotNull() {
            addCriterion("payment_provider is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderEqualTo(String value) {
            addCriterion("payment_provider =", value, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderNotEqualTo(String value) {
            addCriterion("payment_provider <>", value, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderGreaterThan(String value) {
            addCriterion("payment_provider >", value, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderGreaterThanOrEqualTo(String value) {
            addCriterion("payment_provider >=", value, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderLessThan(String value) {
            addCriterion("payment_provider <", value, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderLessThanOrEqualTo(String value) {
            addCriterion("payment_provider <=", value, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderLike(String value) {
            addCriterion("payment_provider like", value, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderNotLike(String value) {
            addCriterion("payment_provider not like", value, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderIn(List<String> values) {
            addCriterion("payment_provider in", values, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderNotIn(List<String> values) {
            addCriterion("payment_provider not in", values, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderBetween(String value1, String value2) {
            addCriterion("payment_provider between", value1, value2, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentProviderNotBetween(String value1, String value2) {
            addCriterion("payment_provider not between", value1, value2, "paymentProvider");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeIsNull() {
            addCriterion("payment_type is null");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeIsNotNull() {
            addCriterion("payment_type is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeEqualTo(Byte value) {
            addCriterion("payment_type =", value, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeNotEqualTo(Byte value) {
            addCriterion("payment_type <>", value, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeGreaterThan(Byte value) {
            addCriterion("payment_type >", value, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("payment_type >=", value, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeLessThan(Byte value) {
            addCriterion("payment_type <", value, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeLessThanOrEqualTo(Byte value) {
            addCriterion("payment_type <=", value, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeIn(List<Byte> values) {
            addCriterion("payment_type in", values, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeNotIn(List<Byte> values) {
            addCriterion("payment_type not in", values, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeBetween(Byte value1, Byte value2) {
            addCriterion("payment_type between", value1, value2, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPaymentTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("payment_type not between", value1, value2, "paymentType");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNull() {
            addCriterion("platform_id is null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIsNotNull() {
            addCriterion("platform_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformIdEqualTo(String value) {
            addCriterion("platform_id =", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotEqualTo(String value) {
            addCriterion("platform_id <>", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThan(String value) {
            addCriterion("platform_id >", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdGreaterThanOrEqualTo(String value) {
            addCriterion("platform_id >=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThan(String value) {
            addCriterion("platform_id <", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLessThanOrEqualTo(String value) {
            addCriterion("platform_id <=", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdLike(String value) {
            addCriterion("platform_id like", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotLike(String value) {
            addCriterion("platform_id not like", value, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdIn(List<String> values) {
            addCriterion("platform_id in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotIn(List<String> values) {
            addCriterion("platform_id not in", values, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdBetween(String value1, String value2) {
            addCriterion("platform_id between", value1, value2, "platformId");
            return (Criteria) this;
        }

        public Criteria andPlatformIdNotBetween(String value1, String value2) {
            addCriterion("platform_id not between", value1, value2, "platformId");
            return (Criteria) this;
        }

        public Criteria andModeIsNull() {
            addCriterion("`mode` is null");
            return (Criteria) this;
        }

        public Criteria andModeIsNotNull() {
            addCriterion("`mode` is not null");
            return (Criteria) this;
        }

        public Criteria andModeEqualTo(Byte value) {
            addCriterion("`mode` =", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeNotEqualTo(Byte value) {
            addCriterion("`mode` <>", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeGreaterThan(Byte value) {
            addCriterion("`mode` >", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeGreaterThanOrEqualTo(Byte value) {
            addCriterion("`mode` >=", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeLessThan(Byte value) {
            addCriterion("`mode` <", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeLessThanOrEqualTo(Byte value) {
            addCriterion("`mode` <=", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeIn(List<Byte> values) {
            addCriterion("`mode` in", values, "mode");
            return (Criteria) this;
        }

        public Criteria andModeNotIn(List<Byte> values) {
            addCriterion("`mode` not in", values, "mode");
            return (Criteria) this;
        }

        public Criteria andModeBetween(Byte value1, Byte value2) {
            addCriterion("`mode` between", value1, value2, "mode");
            return (Criteria) this;
        }

        public Criteria andModeNotBetween(Byte value1, Byte value2) {
            addCriterion("`mode` not between", value1, value2, "mode");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyIsNull() {
            addCriterion("platform_merchant_key is null");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyIsNotNull() {
            addCriterion("platform_merchant_key is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyEqualTo(String value) {
            addCriterion("platform_merchant_key =", value, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyNotEqualTo(String value) {
            addCriterion("platform_merchant_key <>", value, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyGreaterThan(String value) {
            addCriterion("platform_merchant_key >", value, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyGreaterThanOrEqualTo(String value) {
            addCriterion("platform_merchant_key >=", value, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyLessThan(String value) {
            addCriterion("platform_merchant_key <", value, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyLessThanOrEqualTo(String value) {
            addCriterion("platform_merchant_key <=", value, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyLike(String value) {
            addCriterion("platform_merchant_key like", value, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyNotLike(String value) {
            addCriterion("platform_merchant_key not like", value, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyIn(List<String> values) {
            addCriterion("platform_merchant_key in", values, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyNotIn(List<String> values) {
            addCriterion("platform_merchant_key not in", values, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyBetween(String value1, String value2) {
            addCriterion("platform_merchant_key between", value1, value2, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andPlatformMerchantKeyNotBetween(String value1, String value2) {
            addCriterion("platform_merchant_key not between", value1, value2, "platformMerchantKey");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(BigDecimal value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(BigDecimal value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(BigDecimal value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(BigDecimal value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<BigDecimal> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<BigDecimal> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdIsNull() {
            addCriterion("platform_buyer_id is null");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdIsNotNull() {
            addCriterion("platform_buyer_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdEqualTo(String value) {
            addCriterion("platform_buyer_id =", value, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdNotEqualTo(String value) {
            addCriterion("platform_buyer_id <>", value, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdGreaterThan(String value) {
            addCriterion("platform_buyer_id >", value, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdGreaterThanOrEqualTo(String value) {
            addCriterion("platform_buyer_id >=", value, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdLessThan(String value) {
            addCriterion("platform_buyer_id <", value, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdLessThanOrEqualTo(String value) {
            addCriterion("platform_buyer_id <=", value, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdLike(String value) {
            addCriterion("platform_buyer_id like", value, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdNotLike(String value) {
            addCriterion("platform_buyer_id not like", value, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdIn(List<String> values) {
            addCriterion("platform_buyer_id in", values, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdNotIn(List<String> values) {
            addCriterion("platform_buyer_id not in", values, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdBetween(String value1, String value2) {
            addCriterion("platform_buyer_id between", value1, value2, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andPlatformBuyerIdNotBetween(String value1, String value2) {
            addCriterion("platform_buyer_id not between", value1, value2, "platformBuyerId");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredIsNull() {
            addCriterion("time_expired is null");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredIsNotNull() {
            addCriterion("time_expired is not null");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredEqualTo(Long value) {
            addCriterion("time_expired =", value, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredNotEqualTo(Long value) {
            addCriterion("time_expired <>", value, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredGreaterThan(Long value) {
            addCriterion("time_expired >", value, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredGreaterThanOrEqualTo(Long value) {
            addCriterion("time_expired >=", value, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredLessThan(Long value) {
            addCriterion("time_expired <", value, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredLessThanOrEqualTo(Long value) {
            addCriterion("time_expired <=", value, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredIn(List<Long> values) {
            addCriterion("time_expired in", values, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredNotIn(List<Long> values) {
            addCriterion("time_expired not in", values, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredBetween(Long value1, Long value2) {
            addCriterion("time_expired between", value1, value2, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeExpiredNotBetween(Long value1, Long value2) {
            addCriterion("time_expired not between", value1, value2, "timeExpired");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedIsNull() {
            addCriterion("time_created is null");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedIsNotNull() {
            addCriterion("time_created is not null");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedEqualTo(Long value) {
            addCriterion("time_created =", value, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedNotEqualTo(Long value) {
            addCriterion("time_created <>", value, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedGreaterThan(Long value) {
            addCriterion("time_created >", value, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedGreaterThanOrEqualTo(Long value) {
            addCriterion("time_created >=", value, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedLessThan(Long value) {
            addCriterion("time_created <", value, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedLessThanOrEqualTo(Long value) {
            addCriterion("time_created <=", value, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedIn(List<Long> values) {
            addCriterion("time_created in", values, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedNotIn(List<Long> values) {
            addCriterion("time_created not in", values, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedBetween(Long value1, Long value2) {
            addCriterion("time_created between", value1, value2, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeCreatedNotBetween(Long value1, Long value2) {
            addCriterion("time_created not between", value1, value2, "timeCreated");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedIsNull() {
            addCriterion("time_effected is null");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedIsNotNull() {
            addCriterion("time_effected is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedEqualTo(Long value) {
            addCriterion("time_effected =", value, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedNotEqualTo(Long value) {
            addCriterion("time_effected <>", value, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedGreaterThan(Long value) {
            addCriterion("time_effected >", value, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedGreaterThanOrEqualTo(Long value) {
            addCriterion("time_effected >=", value, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedLessThan(Long value) {
            addCriterion("time_effected <", value, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedLessThanOrEqualTo(Long value) {
            addCriterion("time_effected <=", value, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedIn(List<Long> values) {
            addCriterion("time_effected in", values, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedNotIn(List<Long> values) {
            addCriterion("time_effected not in", values, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedBetween(Long value1, Long value2) {
            addCriterion("time_effected between", value1, value2, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andTimeEffectedNotBetween(Long value1, Long value2) {
            addCriterion("time_effected not between", value1, value2, "timeEffected");
            return (Criteria) this;
        }

        public Criteria andMethodIsNull() {
            addCriterion("`method` is null");
            return (Criteria) this;
        }

        public Criteria andMethodIsNotNull() {
            addCriterion("`method` is not null");
            return (Criteria) this;
        }

        public Criteria andMethodEqualTo(Byte value) {
            addCriterion("`method` =", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotEqualTo(Byte value) {
            addCriterion("`method` <>", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThan(Byte value) {
            addCriterion("`method` >", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThanOrEqualTo(Byte value) {
            addCriterion("`method` >=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThan(Byte value) {
            addCriterion("`method` <", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThanOrEqualTo(Byte value) {
            addCriterion("`method` <=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodIn(List<Byte> values) {
            addCriterion("`method` in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotIn(List<Byte> values) {
            addCriterion("`method` not in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodBetween(Byte value1, Byte value2) {
            addCriterion("`method` between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotBetween(Byte value1, Byte value2) {
            addCriterion("`method` not between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(String value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(String value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(String value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(String value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLike(String value) {
            addCriterion("order_type like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotLike(String value) {
            addCriterion("order_type not like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<String> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<String> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(String value1, String value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(String value1, String value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_payment_trades
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}