package com.labijie.application.order.data;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class OrderPaymentTrade implements Cloneable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.payment_provider
     *
     * @mbg.generated
     */
    private String paymentProvider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.payment_type
     *
     * @mbg.generated
     */
    private Byte paymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.platform_id
     *
     * @mbg.generated
     */
    private String platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.mode
     *
     * @mbg.generated
     */
    private Byte mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.platform_merchant_key
     *
     * @mbg.generated
     */
    private String platformMerchantKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.platform_buyer_id
     *
     * @mbg.generated
     */
    private String platformBuyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.time_expired
     *
     * @mbg.generated
     */
    private Long timeExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.time_created
     *
     * @mbg.generated
     */
    private Long timeCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.time_effected
     *
     * @mbg.generated
     */
    private Long timeEffected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.method
     *
     * @mbg.generated
     */
    private Byte method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payment_trades.tag
     *
     * @mbg.generated
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.id
     *
     * @return the value of order_payment_trades.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.id
     *
     * @param id the value for order_payment_trades.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.order_id
     *
     * @return the value of order_payment_trades.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.order_id
     *
     * @param orderId the value for order_payment_trades.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.user_id
     *
     * @return the value of order_payment_trades.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.user_id
     *
     * @param userId the value for order_payment_trades.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.payment_provider
     *
     * @return the value of order_payment_trades.payment_provider
     *
     * @mbg.generated
     */
    public String getPaymentProvider() {
        return paymentProvider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.payment_provider
     *
     * @param paymentProvider the value for order_payment_trades.payment_provider
     *
     * @mbg.generated
     */
    public void setPaymentProvider(String paymentProvider) {
        this.paymentProvider = paymentProvider == null ? null : paymentProvider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.payment_type
     *
     * @return the value of order_payment_trades.payment_type
     *
     * @mbg.generated
     */
    public Byte getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.payment_type
     *
     * @param paymentType the value for order_payment_trades.payment_type
     *
     * @mbg.generated
     */
    public void setPaymentType(Byte paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.platform_id
     *
     * @return the value of order_payment_trades.platform_id
     *
     * @mbg.generated
     */
    public String getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.platform_id
     *
     * @param platformId the value for order_payment_trades.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(String platformId) {
        this.platformId = platformId == null ? null : platformId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.mode
     *
     * @return the value of order_payment_trades.mode
     *
     * @mbg.generated
     */
    public Byte getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.mode
     *
     * @param mode the value for order_payment_trades.mode
     *
     * @mbg.generated
     */
    public void setMode(Byte mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.platform_merchant_key
     *
     * @return the value of order_payment_trades.platform_merchant_key
     *
     * @mbg.generated
     */
    public String getPlatformMerchantKey() {
        return platformMerchantKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.platform_merchant_key
     *
     * @param platformMerchantKey the value for order_payment_trades.platform_merchant_key
     *
     * @mbg.generated
     */
    public void setPlatformMerchantKey(String platformMerchantKey) {
        this.platformMerchantKey = platformMerchantKey == null ? null : platformMerchantKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.amount
     *
     * @return the value of order_payment_trades.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.amount
     *
     * @param amount the value for order_payment_trades.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.platform_buyer_id
     *
     * @return the value of order_payment_trades.platform_buyer_id
     *
     * @mbg.generated
     */
    public String getPlatformBuyerId() {
        return platformBuyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.platform_buyer_id
     *
     * @param platformBuyerId the value for order_payment_trades.platform_buyer_id
     *
     * @mbg.generated
     */
    public void setPlatformBuyerId(String platformBuyerId) {
        this.platformBuyerId = platformBuyerId == null ? null : platformBuyerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.time_expired
     *
     * @return the value of order_payment_trades.time_expired
     *
     * @mbg.generated
     */
    public Long getTimeExpired() {
        return timeExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.time_expired
     *
     * @param timeExpired the value for order_payment_trades.time_expired
     *
     * @mbg.generated
     */
    public void setTimeExpired(Long timeExpired) {
        this.timeExpired = timeExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.time_created
     *
     * @return the value of order_payment_trades.time_created
     *
     * @mbg.generated
     */
    public Long getTimeCreated() {
        return timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.time_created
     *
     * @param timeCreated the value for order_payment_trades.time_created
     *
     * @mbg.generated
     */
    public void setTimeCreated(Long timeCreated) {
        this.timeCreated = timeCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.time_effected
     *
     * @return the value of order_payment_trades.time_effected
     *
     * @mbg.generated
     */
    public Long getTimeEffected() {
        return timeEffected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.time_effected
     *
     * @param timeEffected the value for order_payment_trades.time_effected
     *
     * @mbg.generated
     */
    public void setTimeEffected(Long timeEffected) {
        this.timeEffected = timeEffected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.method
     *
     * @return the value of order_payment_trades.method
     *
     * @mbg.generated
     */
    public Byte getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.method
     *
     * @param method the value for order_payment_trades.method
     *
     * @mbg.generated
     */
    public void setMethod(Byte method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.order_type
     *
     * @return the value of order_payment_trades.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.order_type
     *
     * @param orderType the value for order_payment_trades.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.status
     *
     * @return the value of order_payment_trades.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.status
     *
     * @param status the value for order_payment_trades.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_trades.tag
     *
     * @return the value of order_payment_trades.tag
     *
     * @mbg.generated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_trades.tag
     *
     * @param tag the value for order_payment_trades.tag
     *
     * @mbg.generated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    @Override
    public OrderPaymentTrade clone() throws CloneNotSupportedException {
        return (OrderPaymentTrade) super.clone();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table order_payment_trades
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        orderId("order_id", "orderId", "BIGINT", false),
        userId("user_id", "userId", "BIGINT", false),
        paymentProvider("payment_provider", "paymentProvider", "VARCHAR", false),
        paymentType("payment_type", "paymentType", "TINYINT", false),
        platformId("platform_id", "platformId", "VARCHAR", false),
        mode("mode", "mode", "TINYINT", true),
        platformMerchantKey("platform_merchant_key", "platformMerchantKey", "VARCHAR", false),
        amount("amount", "amount", "DECIMAL", false),
        platformBuyerId("platform_buyer_id", "platformBuyerId", "VARCHAR", false),
        timeExpired("time_expired", "timeExpired", "BIGINT", false),
        timeCreated("time_created", "timeCreated", "BIGINT", false),
        timeEffected("time_effected", "timeEffected", "BIGINT", false),
        method("method", "method", "TINYINT", true),
        orderType("order_type", "orderType", "VARCHAR", false),
        status("status", "status", "TINYINT", true),
        tag("tag", "tag", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order_payment_trades
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}