@file:Suppress("RedundantVisibilityModifier")

package com.labijie.application.identity.`data`.pojo

import kotlin.Long
import kotlin.String

/**
 * POJO for UserLoginTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 * Generator Version: 2.0.10
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.application.identity.data.UserLoginTable
 */
public open class UserLogin {
  public var loginProvider: String = ""

  public var providerKey: String = ""

  public var providerDisplayName: String = ""

  public var userId: Long = 0L
}
