@file:Suppress("RedundantVisibilityModifier")

package com.labijie.application.`data`.aot

import com.labijie.application.model.FileModifier
import com.labijie.infra.orm.aot.registerOrmPojoType
import java.lang.ClassLoader
import org.springframework.aot.hint.MemberCategory
import org.springframework.aot.hint.RuntimeHints
import org.springframework.aot.hint.RuntimeHintsRegistrar

/**
 * SpringBoot runtime hint for orm tables
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 *
 * Generator Version: 2.1.0
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.application.data.FileIndexTable
 */
internal class OrmPojoRuntimeHintsRegistrar : RuntimeHintsRegistrar {
  override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
    // Begin Table Pojo types hint register
    hints.registerOrmPojoType("com.labijie.application.data.pojo.FileIndex")
    hints.registerOrmPojoType("com.labijie.application.data.pojo.LocalizationCode")
    hints.registerOrmPojoType("com.labijie.application.data.pojo.LocalizationLanguage")
    hints.registerOrmPojoType("com.labijie.application.data.pojo.LocalizationMessage")
    hints.registerOrmPojoType("com.labijie.application.data.pojo.TempFileIndex")
    // Begin Column types hint register
    hints.reflection().registerType(FileModifier::class.java) {
      it.withMembers(
      MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
      MemberCategory.INVOKE_PUBLIC_METHODS,
      MemberCategory.DECLARED_FIELDS,
      )
    }
  }
}
