@file:Suppress("RedundantVisibilityModifier")

package com.labijie.application.`data`.pojo

import com.labijie.application.model.FileModifier
import kotlin.Long
import kotlin.String

/**
 * POJO for FileIndexTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 *
 * Generator Version: 2.1.0
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.application.data.FileIndexTable
 */
public open class FileIndex {
  public var path: String = ""

  public var timeCreated: Long = 0L

  public var fileType: String = ""

  public var sizeIntBytes: Long = 0L

  public var entityId: Long = 0L

  public var fileAccess: FileModifier = FileModifier.Public

  public var id: Long = 0L
}
