@file:Suppress("RedundantVisibilityModifier")

package com.labijie.application.`data`.pojo

import kotlin.String

/**
 * POJO for LocalizationMessageTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 *
 * Generator Version: 2.1.1
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.application.data.LocalizationMessageTable
 */
public open class LocalizationMessage {
  public var locale: String = ""

  public var code: String = ""

  public var message: String = ""
}
