@file:Suppress("RedundantVisibilityModifier")

package com.labijie.application.`data`.pojo

import kotlin.Boolean
import kotlin.String

/**
 * POJO for LocalizationLanguageTable
 *
 * This code generated by an open-source project: Infra-Orm 
 * Project Site: https://github.com/hongque-pro/infra-orm.
 *
 * Generator Version: 2.1.0
 *
 *
 * Don't modify these codes !!
 *
 * Origin Exposed Table:
 * @see com.labijie.application.data.LocalizationLanguageTable
 */
public open class LocalizationLanguage {
  public var locale: String = ""

  public var language: String = ""

  public var country: String = ""

  public var disabled: Boolean = false

  public var default: Boolean = false
}
