package com.labijie.application.web.data.mapper;

import com.labijie.application.web.data.domain.RegionCity;
import com.labijie.application.web.data.domain.RegionCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RegionCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    long countByExample(RegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    int deleteByExample(RegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    int insert(RegionCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    int insertSelective(RegionCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    List<RegionCity> selectByExampleWithRowbounds(RegionCityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<RegionCity> selectByExampleSelective(@Param("example") RegionCityExample example, @Param("selective") RegionCity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    List<RegionCity> selectByExample(RegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RegionCity selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") RegionCity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    RegionCity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RegionCity record, @Param("example") RegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RegionCity record, @Param("example") RegionCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RegionCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RegionCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<RegionCity> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_city
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<RegionCity> list, @Param("selective") RegionCity.Column ... selective);
}