package com.labijie.application.web.data.mapper;

import com.labijie.application.web.data.domain.RegionProvince;
import com.labijie.application.web.data.domain.RegionProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RegionProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    long countByExample(RegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    int deleteByExample(RegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    int insert(RegionProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    int insertSelective(RegionProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    List<RegionProvince> selectByExampleWithRowbounds(RegionProvinceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<RegionProvince> selectByExampleSelective(@Param("example") RegionProvinceExample example, @Param("selective") RegionProvince.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    List<RegionProvince> selectByExample(RegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RegionProvince selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") RegionProvince.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    RegionProvince selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RegionProvince record, @Param("example") RegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RegionProvince record, @Param("example") RegionProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RegionProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RegionProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<RegionProvince> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_region_province
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<RegionProvince> list, @Param("selective") RegionProvince.Column ... selective);
}